// server.js
const express = require("express");
const cors = require("cors");

const app = express();
const PORT = 4000;

// Enable CORS so other frontends can access this API
app.use(cors());

// Sample data (your 30 rows)
const rowData = [
    {
    category: "Category 1",
    program: "Program A",
    spendingDriver: "Driver X",
    total: 12345,
    dept: "Finance",
    site: "NY Office",
    modifiedBy: "Alice",
    updateTimestamp: "2025-06-15T10:30:00Z",
  },
  {
    category: "Category 2",
    program: "Program B",
    spendingDriver: "Driver Y",
    total: 67890,
    dept: "Marketing",
    site: "LA Office",
    modifiedBy: "Bob",
    updateTimestamp: "2025-06-14T09:15:00Z",
  },
  {
    category: "Category 3",
    program: "Program C",
    spendingDriver: "Driver Z",
    total: 54321,
    dept: "Operations",
    site: "Chicago Office",
    modifiedBy: "Carol",
    updateTimestamp: "2025-06-13T08:00:00Z",
  },
  {
    category: "Category 4",
    program: "Program D",
    spendingDriver: "Driver W",
    total: 98765,
    dept: "HR",
    site: "Boston Office",
    modifiedBy: "Dave",
    updateTimestamp: "2025-06-12T14:45:00Z",
  },
  {
    category: "Category 1",
    program: "Program E",
    spendingDriver: "Driver X",
    total: 11111,
    dept: "Finance",
    site: "NY Office",
    modifiedBy: "Eve",
    updateTimestamp: "2025-06-11T09:30:00Z",
  },
  {
    category: "Category 2",
    program: "Program F",
    spendingDriver: "Driver Y",
    total: 22222,
    dept: "Marketing",
    site: "LA Office",
    modifiedBy: "Frank",
    updateTimestamp: "2025-06-10T16:20:00Z",
  },
  {
    category: "Category 3",
    program: "Program G",
    spendingDriver: "Driver Z",
    total: 33333,
    dept: "Operations",
    site: "Chicago Office",
    modifiedBy: "Grace",
    updateTimestamp: "2025-06-09T11:00:00Z",
  },
  {
    category: "Category 4",
    program: "Program H",
    spendingDriver: "Driver W",
    total: 44444,
    dept: "HR",
    site: "Boston Office",
    modifiedBy: "Heidi",
    updateTimestamp: "2025-06-08T15:15:00Z",
  },
  {
    category: "Category 1",
    program: "Program I",
    spendingDriver: "Driver X",
    total: 55555,
    dept: "Finance",
    site: "NY Office",
    modifiedBy: "Ivan",
    updateTimestamp: "2025-06-07T10:10:00Z",
  },
  {
    category: "Category 2",
    program: "Program J",
    spendingDriver: "Driver Y",
    total: 66666,
    dept: "Marketing",
    site: "LA Office",
    modifiedBy: "Judy",
    updateTimestamp: "2025-06-06T13:30:00Z",
  },
  {
    category: "Category 3",
    program: "Program K",
    spendingDriver: "Driver Z",
    total: 77777,
    dept: "Operations",
    site: "Chicago Office",
    modifiedBy: "Karl",
    updateTimestamp: "2025-06-05T09:00:00Z",
  },
  {
    category: "Category 4",
    program: "Program L",
    spendingDriver: "Driver W",
    total: 88888,
    dept: "HR",
    site: "Boston Office",
    modifiedBy: "Lara",
    updateTimestamp: "2025-06-04T17:45:00Z",
  },
  {
    category: "Category 1",
    program: "Program M",
    spendingDriver: "Driver X",
    total: 99999,
    dept: "Finance",
    site: "NY Office",
    modifiedBy: "Mike",
    updateTimestamp: "2025-06-03T12:15:00Z",
  },
  {
    category: "Category 2",
    program: "Program N",
    spendingDriver: "Driver Y",
    total: 10101,
    dept: "Marketing",
    site: "LA Office",
    modifiedBy: "Nina",
    updateTimestamp: "2025-06-02T11:45:00Z",
  },
  {
    category: "Category 3",
    program: "Program O",
    spendingDriver: "Driver Z",
    total: 20202,
    dept: "Operations",
    site: "Chicago Office",
    modifiedBy: "Oscar",
    updateTimestamp: "2025-06-01T14:00:00Z",
  },
  {
    category: "Category 4",
    program: "Program P",
    spendingDriver: "Driver W",
    total: 30303,
    dept: "HR",
    site: "Boston Office",
    modifiedBy: "Pam",
    updateTimestamp: "2025-05-31T10:30:00Z",
  },
  {
    category: "Category 1",
    program: "Program Q",
    spendingDriver: "Driver X",
    total: 40404,
    dept: "Finance",
    site: "NY Office",
    modifiedBy: "Quinn",
    updateTimestamp: "2025-05-30T16:45:00Z",
  },
  {
    category: "Category 2",
    program: "Program R",
    spendingDriver: "Driver Y",
    total: 50505,
    dept: "Marketing",
    site: "LA Office",
    modifiedBy: "Ray",
    updateTimestamp: "2025-05-29T09:20:00Z",
  },
  {
    category: "Category 3",
    program: "Program S",
    spendingDriver: "Driver Z",
    total: 60606,
    dept: "Operations",
    site: "Chicago Office",
    modifiedBy: "Sue",
    updateTimestamp: "2025-05-28T13:15:00Z",
  },
  {
    category: "Category 4",
    program: "Program T",
    spendingDriver: "Driver W",
    total: 70707,
    dept: "HR",
    site: "Boston Office",
    modifiedBy: "Tom",
    updateTimestamp: "2025-05-27T15:00:00Z",
  },
  {
    category: "Category 1",
    program: "Program U",
    spendingDriver: "Driver X",
    total: 80808,
    dept: "Finance",
    site: "NY Office",
    modifiedBy: "Uma",
    updateTimestamp: "2025-05-26T11:10:00Z",
  },
  {
    category: "Category 2",
    program: "Program V",
    spendingDriver: "Driver Y",
    total: 90909,
    dept: "Marketing",
    site: "LA Office",
    modifiedBy: "Vince",
    updateTimestamp: "2025-05-25T14:50:00Z",
  },
  {
    category: "Category 3",
    program: "Program W",
    spendingDriver: "Driver Z",
    total: 10010,
    dept: "Operations",
    site: "Chicago Office",
    modifiedBy: "Wendy",
    updateTimestamp: "2025-05-24T12:25:00Z",
  },
  {
    category: "Category 4",
    program: "Program X",
    spendingDriver: "Driver W",
    total: 11111,
    dept: "HR",
    site: "Boston Office",
    modifiedBy: "Xander",
    updateTimestamp: "2025-05-23T16:30:00Z",
  },
  {
    category: "Category 1",
    program: "Program Y",
    spendingDriver: "Driver X",
    total: 12121,
    dept: "Finance",
    site: "NY Office",
    modifiedBy: "Yara",
    updateTimestamp: "2025-05-22T10:05:00Z",
  },
  {
    category: "Category 2",
    program: "Program Z",
    spendingDriver: "Driver Y",
    total: 13131,
    dept: "Marketing",
    site: "LA Office",
    modifiedBy: "Zack",
    updateTimestamp: "2025-05-21T13:40:00Z",
  },
  {
    category: "Category 3",
    program: "Program AA",
    spendingDriver: "Driver Z",
    total: 14141,
    dept: "Operations",
    site: "Chicago Office",
    modifiedBy: "Anna",
    updateTimestamp: "2025-05-20T15:55:00Z",
  },
  {
    category: "Category 4",
    program: "Program BB",
    spendingDriver: "Driver W",
    total: 15151,
    dept: "HR",
    site: "Boston Office",
    modifiedBy: "Ben",
    updateTimestamp: "2025-05-19T09:35:00Z",
  },
  {
    category: "Category 1",
    program: "Program CC",
    spendingDriver: "Driver X",
    total: 16161,
    dept: "Finance",
    site: "NY Office",
    modifiedBy: "Cathy",
    updateTimestamp: "2025-05-18T11:20:00Z",
  },
  {
    category: "Category 2",
    program: "Program DD",
    spendingDriver: "Driver Y",
    total: 17171,
    dept: "Marketing",
    site: "LA Office",
    modifiedBy: "Dan",
    updateTimestamp: "2025-05-17T14:00:00Z",
  }
  ];

// API endpoint
app.get("/api/data", (req, res) => {
  setTimeout(()=>res.json(rowData),1000)
});

app.get("/api/login", (req, res) => {
    setTimeout(()=>res.json(rowData),2000)
});

// Start server
app.listen(PORT, () => {
  console.log(`Express server running on http://localhost:${PORT}`);
});
