import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import 'bootstrap/dist/css/bootstrap.min.css';
import Footer from "@/components/Footer";
import SidebarNavigation from "@/components/SideNavbar";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen flex flex-col">
          {/* Top Navigation Bar */}
          <Navbar />

          {/* Main Layout Container */}
          <div className="flex flex-1 h-full">
            {/* Sidebar Navigation */}
            <SidebarNavigation />
            <main className="flex-1 bg-gray-50 flex flex-col justify-between">
              {children}
              <Footer />
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
