import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import 'bootstrap/dist/css/bootstrap.min.css';
import Footer from "@/components/Footer";
import SidebarNavigation from "@/components/SideNavbar";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}>
        <Navbar />
        <div className="flex flex-1 overflow-hidden">
          <SidebarNavigation />
          {/* Content Area with scrollable children */}
          <main className="flex-1 flex flex-col overflow-hidden bg-gray-50">
            <div className="flex-1 overflow-y-auto">
              {children}
            </div>
            <Footer />
          </main>
        </div>
      </body>
    </html>
  );
}